
name: First Workflow

on: push

jobs:
  my-first-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Coping code
        uses: actions/checkout@v6

      - name: name node-js
        uses: actions/setup-node@v6
        with:
          node-version: 20.19.5
          
      - name: check node version
        run: node -v


