
name: First Workflow

on: push

jobs:
  test-code:
    runs-on: ubuntu-latest

    steps:
      - name: Coping code
        uses: actions/checkout@v6

      - name: install node-js
        uses: actions/setup-node@v6
        with:
          node-version: 24.11.1

      - name: check node version
        run: node -v

      - name: install dependencies
        run: npm install
        
      - name : run tests
        run: npm run lint


  build-code:
    runs-on: ubuntu-latest

    steps:
      - name: install node-js
        uses: actions/setup-node@v6
        with:
          node-version: 24.11.1

      - name: Coping code
        uses: actions/checkout@v6

      - name: install dependencies
        run: npm install

      - name: build project
        run: npm run build
