

# name: First Workflow

# on: push 

# jobs:
#   my-first-jobs:
#     runs-on: ubuntu-latest

#     steps:
#         - name: Print Message
#           run: echo "Hello github action"
        
#         - name: Check Linting
#           run: echo "check linting"

name: First Workflow

on: push

jobs:
  my-first-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: echo "Hello github"

      - name: Check Linting
        run: echo "check linting"
 