
name: First Workflow

on: push

jobs:
  my-first-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Print Work Directory
        run: |
          pwd
          ls -a 
          echo $GITHUB_WORKSPACE