
# name: First Workflow

# on: push

# jobs:
#   my-first-jobs:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Coping code
#         uses: actions/checkout@v6

#       - name: name node-js
#         uses: actions/checkout@v6
#         with:
#           node-version: 20.19.5
#       - name: check node version
#         run: node -v


name: First Workflow

on: push

jobs:
  my-first-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Coping code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.5

      - name: check node version
        run: node -v
